### ISSUE TITLE
Help Needed, Resulted Trained agent?

### ISSUE THREAD

**Issue by misterabdullahAziz** [nadavbh12/Retro-Learning-Environment#6]
1. how to add new game?
2. where is final result of trained agent?
3. How to switch dqn with ddqn d-ddqn?

I am all new in this So your help will be highly appreciated. Thanks, Looking forward.

**Comment by nadavbh12** [comment]
Hi,

1. We created a [wiki page](https://github.com/nadavbh12/Retro-Learning-Environment/wiki/How-to-add-a-new-game) with instructions for adding a new game.

2. and 3. This repository is an environment on which you can train a variety of agents. The only agents provided here are sample agents in C++ and Python.
You can check out our [fork of deep_q_rl](https://github.com/nadavbh12/deep_q_rl) which runs the basic DQN on top of RLE in Python.
Porting other implementation to use RLE rather than ALE should be fairly simple as the interface is mostly the same.
